# Generated by Django 5.0.2 on 2024-02-11 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_options_client_team_alter_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='description',
        ),
    ]
